### ISSUE TITLE
docker build fails when @livingdocs/docker is npm linked

### ISSUE THREAD

**Issue by masone** [upfrontIO/livingdocs-docker#8]
Docker cannot reference / add symlinked files during a `docker build`. This is the case when `@livingdocs/docker` is linked via `npm link` for testing. 

```
Step 4 : ADD node_modules/@livingdocs/docker/editor/bin/dumb-init /sbin/dumb-init
lstat node_modules/@livingdocs/docker/editor/bin/dumb-init: no such file or directory
```

**Comment by masone** [comment]
It looks like docker is not planning support for symlinks https://github.com/docker/docker/issues/1676

**Comment by marcbachmann** [comment]
I'd use tar and build the container that way instead of the path `.`
I haven't tried this, but it should work:
```
docker build < tar -cfz - .
```

By using that we can also get rid of the build path problem that the docker file must be in a subdir of the docker file.

**Comment by marcbachmann** [comment]
That's actually working: `tar -cfz . | docker build -`

**Comment by masone** [comment]
> If you use STDIN or specify a URL, the system places the contents into a file called Dockerfile, and any -f, --file option is ignored. In this scenario, there is no context.

From the docs at https://docs.docker.com/engine/reference/commandline/build/. I'm not sure how adding files works if there is no context.

**Comment by marcbachmann** [comment]
I suppose that doc is wrong. I think you don't have any context besides the files in the tar file. But you have full access to all the files in the tar. But I'm not sure about that.

**Comment by masone** [comment]
That would totally make sense. It might be hard to educate everyone to issue such a "special" build command. Also in parallel, I had to adapt the setup slightly and this problem does not apply anymore with https://github.com/upfrontIO/livingdocs-docker/pull/9
